server:
  port: 9999

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4201"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: products-service
          uri: lb://MICROSERVICE-PRODUIT
          predicates:
            - Path=/microservice-produit/**
          filters:
            - StripPrefix=1
        - id: commands-service
          uri: lb://MICROSERVICE-COMMANDES
          predicates:
            - Path=/microservice-commandes/**
          filters:
            - StripPrefix=1
    config:
      uri: http://localhost:8888
      fail-fast: true
      username: config-server
      password: config-server-password

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
